repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
    -   id: yapf
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-case-conflict
-   repo: https://github.com/lovesegfault/beautysh
    rev: v6.1.0
    hooks:
    -   id: beautysh
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.1
    hooks:
    -   id: docker-compose-check
-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint
